app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)   

    def __repr__(self):
        return f'User {self.username} '


class Admin(UserMixin,db.Model):
    __tablename__ = 'admins'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)   

    def __repr__(self):
        return f'User {self.username} '


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")
    admins = db.relationship('Admin',backref = 'role',lazy="dynamic")



    def __repr__(self):
        return f'User {self.name}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    '''
    UpdateProfile class for bio updates
    '''
    bio = TextAreaField('Express your thoughts.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask import Blueprint
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()


auth = Blueprint('auth',__name__)

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors


def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required, current_user
from ..models import User,Role,Admin
from .forms import UpdateProfile
from .. import db,photos

# Views
@main.route('/')
def index():
    '''Index method to display the main index page
    '''
    title = "EventsPhotography"
   
    return render_template('index.html' ,title = title)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{% block navbar %}
    {% include "navbar.html" %}
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}


{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock%}

{% block content %}
    <body>

        <header>
            <div class="overlay"></div>
            <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
              <source src="https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4" type="video/mp4">
            </video>
            <div class="container h-100">
              <div class="d-flex h-100 text-center align-items-center">
                <div class="w-100 text-white">
                  <img src="https://unixtitan.net/images/camera-clipart-black-and-white-png-5.png" alt="" style="height:200px; witdth:300px; color:#ffff">
                  <h1 class="display-3" style="color:#ffff;font-family: 'Kaushan Script', cursive;line-height: 300px; font-size: 70px; margin-top:-140px ">PHOTO-PORTAL</h1>
                  <a href="" class="btn btn-danger">PHOTOGRAPHER</a>
                  <a href="{{url_for('auth.login')}}" class="btn btn-info">GUEST</a>
                </div>
              </div>
            </div>
        </header>
        <div class="container content" style="margin-bottom:100px">
          <h1 style="text-align:center; margin-top: 100px; margin-bottom:100px">CATEGORIES</h1>
          <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <img src="https://images.unsplash.com/photo-1544954766-cc536df31678?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="" style="height:300px; width:260px">
            <p><a href="">Weddings</a></p>
          </div>
          <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <img src="https://images.unsplash.com/photo-1505964135045-cdada2f6bf43?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="" style="height:300px; width:260px">
            
            <p><a href="">Concerts</a></p>
          </div>
          <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <img src="https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="" style="height:300px; width:260px">
            <p><a href="">Team building events</a></p>
          </div>
          <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <img src="https://www.corpgov.net/wp-content/uploads/2009/12/conference.jpeg" alt="" style="height:300px; width:260px">
            <p><a href="">conferences</a></p>

          </div>
          <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <img src="http://www.scottsdalepremierlimos.com/uploads/5/7/6/1/57618509/1439102_orig.jpg" alt="" style="height:300px; width:260px">
            <p><a href="">sports events</a></p>
          </div>

          <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <img src="https://images.unsplash.com/photo-1523753917948-e1cb9cbc5913?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt=""style="height:300px; width:260px">
             <p><a href="">Promotion events</a></p>
          </div>


          <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
              <img src="https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="" style="height:300px; width:260px">
              <p><a href="">party time events</a></p>
            </div>

            <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
              <img src="https://images.unsplash.com/photo-1521961835394-3ffc4d600e40?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" style="height:300px; width:260px">
              <p><a href="">after party</a></p>
            </div>
            
        </div>
            
        </div>
        <div class="free-section">

        </div>
        <div class="subscribe">
          <h1 style="text-align: center; margin-top: 100px">SUBSCRIBE TO GET UPDATES ON UPCOMING EVENTS</h1>
          <form style="width:500px; margin: auto ; padding: 40px; margin-bottom:100px;margin-top:100px"  class="jumbotron">
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div>
              <button type="submit" class="btn btn-primary subscribe" onclick="subscribe()">Submit</button>
            </form>
            
        </div>
        <footer class="section footer-classic context-dark bg-image" style="background: #2d3246;">
          <div class="container">
            <div class="row row-30">
              <div class="col-md-4 col-xl-5">
                <div class="pr-xl-4"><a class="brand" href="index.html"><img class="brand-logo-light" src="images/agency/logo-inverse-140x37.png" alt="" width="140" height="37" srcset="images/agency/logo-retina-inverse-280x74.png 2x"></a>
                  <p>We are Events and photography majoured ajency in Moringa Kenya . We hook up proffesional Photographers to the market and guests with their desired photos. We majourly focus on planning and marketing.</p>
                  <!-- Rights-->
                  <p class="rights"><span>©  </span><span class="copyright-year">2019</span><span> </span><span>Events-Photography</span><span>. </span><span>All Rights Reserved.</span></p>
                </div>
              </div>
              <div class="col-md-4">
                <h5>Contacts</h5>
                <dl class="contact-list">
                  <dt>Address:</dt>
                  <dd>Ngong-Road Moringa school</dd>
                </dl>
                <dl class="contact-list">
                  <dt>email:</dt>
                  <dd><a href="mailto:#">eventsphotography@gmail.com</a></dd>
              </dl>
              <dl class="contact-list">
                <dt>phones:</dt>
                <dd><a href="tel:#">+254 722 586 098</a> <span>or</span> <a href="tel:#">+254 708 486 367 </a>
                </dd>
              </dl>
            </div>
            <div class="col-md-4 col-xl-3">
              <h5>Links</h5>
              <ul class="nav-list" style="display:inline; margin: 10px">
                <li><a href="#">About</a></li>
                <li><a href="#">Projects</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Contacts</a></li>
                <li><a href="#">Pricing</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row no-gutters social-container">
          <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-facebook"></span><span>Facebook</span></a></div>
          <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-instagram"></span><span>instagram</span></a></div>
          <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-twitter"></span><span>twitter</span></a></div>
          <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-youtube-play"></span><span>google</span></a></div>
        </div>
      </footer>








        <style>
          @import url('https://fonts.googleapis.com/css?family=Kaushan+Script');
          header {
          position: relative;
          background-color: black;
          height: 75vh;
          min-height: 25rem;
          width: 100%;
          overflow: hidden;
          background-attachment: fixed;
        }
        .category img{
          margin-right:10px;
        }
        
        header video {
          position: absolute;
          top: 50%;
          left: 50%;
          min-width: 100%;
          min-height: 100%;
          width: auto;
          height: auto;
          z-index: 0;
          -ms-transform: translateX(-50%) translateY(-50%);
          -moz-transform: translateX(-50%) translateY(-50%);
          -webkit-transform: translateX(-50%) translateY(-50%);
          transform: translateX(-50%) translateY(-50%);
        }
        
        header .container {
          position: relative;
          z-index: 2;
        }
        
        header .overlay {
          position: absolute;
          top: 0;
          left: 0;
          height: 100%;
          width: 100%;
          background-color: black;
          opacity: 0.8;
          z-index: 1;
        }
        .free-section{
          height: 500px;
          width: 100%;
          background-attachment: fixed;
          background-image: url("https://crokepark.ie/BlankSite/media/optimised/Home/EOTF-590.jpg?ext=.jpg");
          background-repeat: no-repeat;
        }
        
        @media (pointer: coarse) and (hover: none) {
          header {
            background: url('https://source.unsplash.com/XT5OInaElMw/1600x900') black no-repeat center center scroll;
          }
          header video {
            display: none;
          }
        }

        .context-dark, .bg-gray-dark, .bg-primary {
          color: rgba(255, 255, 255, 0.8);
      }

      .footer-classic a, .footer-classic a:focus, .footer-classic a:active {
          color: #ffffff;
      }
      .nav-list li {
          padding-top: 5px;
          padding-bottom: 5px;
      }

      .nav-list li a:hover:before {
          margin-left: 0;
          opacity: 1;
          visibility: visible;
      }

      ul, ol {
          list-style: none;
          padding: 0;
          margin: 0;
      }

      .social-inner {
          display: flex;
          flex-direction: column;
          align-items: center;
          width: 100%;
          padding: 23px;
    font: 900 13px/1 "Lato", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    text-transform: uppercase;
    color: rgba(255, 255, 255, 0.5);
}
.social-container .col {
    border: 1px solid rgba(255, 255, 255, 0.1);
}
.nav-list li a:before {
    content: "\f14f";
    font: 400 21px/1 "Material Design Icons";
    color: #4d6de6;
    display: inline-block;
    vertical-align: baseline;
    margin-left: -28px;
    margin-right: 7px;
    opacity: 0;
    visibility: hidden;
    transition: .22s ease;
}

              
              </style>
              <script>
              function subscribe(){
                
                            Swal.fire({
                    position: 'top',
                    type: 'success',
                    title: 'You have been succesfully subsribed!!',
                    showConfirmButton: false,
                    timer: 1500
                  })
              }
        </script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
        <script src="sweetalert2.all.min.js"></script>
    </body>
{% endblock %}

app/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
        body {
          font-family: "Lato", sans-serif;
        }
        
        .sidenav {
          height: 100%;
          width: 0;
          position: fixed;
          z-index: 1;
          top: 0;
          left: 0;
          background-color: #111;
          overflow-x: hidden;
          transition: 0.5s;
          padding-top: 60px;
        }
        
        .sidenav a {
          padding: 8px 8px 8px 32px;
          text-decoration: none;
          font-size: 25px;
          color: #818181;
          display: block;
          transition: 0.3s;
        }
        
        .sidenav a:hover {
          color: #f1f1f1;
        }
        
        .sidenav .closebtn {
          position: absolute;
          top: 0;
          right: 25px;
          font-size: 36px;
          margin-left: 50px;
        }
        
        @media screen and (max-height: 450px) {
          .sidenav {padding-top: 15px;}
          .sidenav a {font-size: 18px;}
        }
        </style>
</head>
<body>
    <div id="mySidenav" class="sidenav" style="z-index:999">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="/">Home</a>
        <!-- <a href="#">Quotes</a> -->
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a></li>
          <li><a href="{{url_for('auth.logout')}}" style="list-style: none;">Sign out</a></li>
          {% else %}
          <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
                
    </div>
        
    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
    <script>
            function openNav() {
              document.getElementById("mySidenav").style.width = "250px";
            }
      
            function closeNav() {
              document.getElementById("mySidenav").style.width = "0";
            }
    </script>
</body>
</html>

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}
    
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" style="border-radius: 60% ; width: 200px; height: 200px; margin-top: 60px ">
    <p style="font-weight:bold;font-size:20px;"> {{user.username| capitalize}} </p>
    {%else%}
    <p>No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data" style="padding-top:60px;">

      <form-group>
        <input type="file"  name="photo" class="form-control" required>
        <input type="submit">
      </form-group>
      <br>
      <br>
      <br>
      
    </form>

    <div class="row categories1">
      <h1>Events</h1>
      <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <p><a href="/">Pickup lines</a></p>
      </div>
      <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <p><a href="/">Interview pitch</a></p>
      </div>
      <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <p><a href="/">product pitch</a></p>
      </div>

      <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <p><a href="/">Promotion pitch</a></p>
      </div>
  </div>
  <div class="row categories2">
    <h1>Photographers</h1>
      <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <p><a href="/">Pickup lines</a></p>
      </div>
      <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <p><a href="/">Interview pitch</a></p>
      </div>
      <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <p><a href="/">product pitch</a></p>
      </div>

      <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <p><a href="/">Promotion pitch</a></p>
      </div>
  </div>
    
      {% endif %}
      
    
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}